---
type: media_leaf

media_leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    loopback_ipv4_pool: 192.168.98.0/27
    loopback_ipv4_offset: 2
    # Offset must be >= number of spines
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 192.168.98.32/27
    uplink_switches: [jt-nm-amber-spine-1,jt-nm-amber-spine-1]
    uplink_interfaces: [Ethernet49/1, Ethernet50/1]
    max_parallel_uplinks: 2 # per leaf / per spine
  nodes:
      jt-nm-amber-leaf-1:
        platform: 7050X3
        #loopback = pool+offset+ID
        id: 1
        bgp_as: 65011
        mgmt_ip: 192.168.0.6
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet1/1, Ethernet2/1]
      jt-nm-amber-leaf-2:
        platform: 7050X3
        id: 2
        bgp_as: 65012
        mgmt_ip: 192.168.0.7
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet3/1, Ethernet4/1]
      jt-nm-amber-leaf-3:
        platform: 7280R2
        id: 3
        bgp_as: 65013
        mgmt_ip: 192.168.0.8
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet5/1, Ethernet6/1]
      jt-nm-amber-leaf-4:
        platform: 720XP
        id: 4
        bgp_as: 65014
        mgmt_ip: 192.168.0.9
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet7/1, Ethernet7/2]
        uplink_interfaces: [Ethernet49, Ethernet50]
        uplink_interface_speed: 10000full
      jt-nm-amber-leaf-5:
        platform: 7020R
        id: 5
        bgp_as: 65015
        mgmt_ip: 192.168.0.11
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet9/1, Ethernet10/1]
        uplink_interfaces: [Ethernet49, Ethernet50]
        ptp:
          priority1: 10