---
type: media_leaf

media_leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    loopback_ipv4_pool: 192.168.99.0/27
    # Offset must be >= number of spines
    loopback_ipv4_offset: 2
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 192.168.99.64/27
    uplink_switches: [jt-nm-blue-spine-1, jt-nm-blue-spine-1]
    uplink_interfaces: [Ethernet49/1, Ethernet50/1]
    max_parallel_uplinks: 2 # per leaf / per spine
  nodes:
      jt-nm-blue-leaf-1:
        platform: 7280R2
        id: 1
        bgp_as: 65021
        mgmt_ip: 192.168.0.12
        # Interfaces configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet1/1, Ethernet2/1]
      jt-nm-blue-leaf-2:
        platform: 7280R2
        id: 2
        bgp_as: 65022
        mgmt_ip: 192.168.0.13
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet3/1, Ethernet4/1]
      jt-nm-blue-leaf-3:
        platform: 7050X2
        id: 3
        bgp_as: 65023
        mgmt_ip: 192.168.0.14
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet5/1, Ethernet6/1]
      jt-nm-blue-leaf-4:
        platform: 720XP
        id: 4
        bgp_as: 65024
        mgmt_ip: 192.168.0.15
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet7/1, Ethernet7/2]
        uplink_interfaces: [Ethernet49, Ethernet50]
        uplink_interface_speed: 10000full
      jt-nm-blue-leaf-5:
        platform: 7020R
        id: 5
        bgp_as: 65025
        mgmt_ip: 192.168.0.16
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet9/1, Ethernet10/1]
        uplink_interfaces: [Ethernet49, Ethernet50]
        ptp:
          priority1: 10

