---
type: media_spine

media_spine:
  defaults:
    platform: 7280R3
    bgp_as: 65010
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # Overlay loopback IP and same pool can be assigned to both spine and l3leaf switches
    # If same loopback pool is defined for both spine and l3leaf,
    # < loopback_ipv4_offset > must be set in either one of the node_types
    loopback_ipv4_pool: 192.168.98.0/27
    uplink_ipv4_pool: 192.168.98.92/27
    # Recommended for vEOS
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart' 
  nodes:
    jt-nm-amber-spine-1:
      #loopback0 = pooladdress + ID
      id: 1
      mgmt_ip: 192.168.0.5
      # Interfaces configured on MGT SPINE to connect to this spine
      uplink_switch_interfaces: [Ethernet49]
      uplink_switches: [jt-nm-mgt-1]
      uplink_interfaces: [Ethernet7/3]
      uplink_interface_speed: 10000full
      # Remember we don't have PTP Priority1 yet


