---
type: mgt_spine

mgt_spine:
  defaults:
    platform: 720XP
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.97.0/27
    # Recommended for vEOS
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    jt-nm-mgt-1:
      id: 1
      mgmt_ip: 192.168.0.1


    







