---
type: l3leaf

l3leaf:
  defaults:
    platform: EOS
    #bgp_as: 65002
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
    # Assign range larger than total leaf switches
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    loopback_ipv4_pool: 192.168.99.0/27
    # Offset must be >= number of spines
    loopback_ipv4_offset: 2
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 192.168.99.64/27
    uplink_switches: [jt-nm-blue-spine-1, jt-nm-blue-spine-1]
    uplink_interfaces: [Ethernet49/1, Ethernet50/1]
    #mlag_interfaces: [Ethernet3, Ethernet4]
    # mlag pair IP assignment - assign blocks - Assign range larger than
    # total spines + total leafs switches
    #mlag_peer_ipv4_pool: 10.255.252.0/24
    #mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  nodes:
      jt-nm-blue-leaf-1:
        id: 1
        bgp_as: 65021
        mgmt_ip: 10.90.227.25
        # Interfaces configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet1/1, Ethernet2/1]
        ptp:  
        priority1: 20
        priority2: 21
      jt-nm-blue-leaf-2:
        id: 2
        bgp_as: 65022
        mgmt_ip: 10.90.227.27
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet3/1, Ethernet4/1]
        ptp:  
        priority1: 20
        priority2: 22
      jt-nm-blue-leaf-3:
        id: 3
        bgp_as: 65023
        mgmt_ip: 10.90.227.29
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet5/1, Ethernet6/1]
        ptp:  
        priority1: 20
        priority2: 23
      jt-nm-blue-leaf-4:
        id: 4
        bgp_as: 65024
        mgmt_ip: 10.90.227.31
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet7/1, Ethernet7/2]
        ptp:  
        priority1: 20
        priority2: 24
      jt-nm-blue-leaf-5:
        id: 5
        bgp_as: 65025
        mgmt_ip: 10.90.227.31
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet9/1, Ethernet10/1]
        ptp:  
        priority1: 20
        priority2: 25
custom_structured_configuration_ethernet_interfaces:
  Ethernet49/1:
    pim:
      ipv4:
        sparse_mode: true
  Ethernet50/1:
    pim:
      ipv4:
        sparse_mode: true