---
type: media_spine

media_spine:
  defaults:
    platform: 7280R3
    bgp_as: 65020
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # Overlay loopback IP and same pool can be assigned to both spine and l3leaf switches
    # If same loopback pool is defined for both spine and l3leaf,
    # < loopback_ipv4_offset > must be set in either one of the node_types
    loopback_ipv4_pool: 192.168.99.0/27
    uplink_ipv4_pool: 192.168.99.92/27
    # Recommended for vEOS
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    jt-nm-blue-spine-1:
    #loopback0 = pooladdress + ID
      id: 1
      mgmt_ip: 192.168.0.11
      # Interfaces configured on mgt spines to connect to this spine
      uplink_switch_interfaces: [Ethernet50]
      uplink_switches: [jt-nm-mgt-1]
      uplink_interfaces: [Ethernet7/3]
      uplink_intreface_speed: 10000full




