---
pod_name: JT_NM_MGT_LEAFS
type: mgt_leaf

mgt_leaf:
  defaults:
    uplink_switches: [jt-nm-mgt-1]
    uplink_interfaces: [Ethernet49]
  nodes:
      jt-nm-mgt-2:
        platform: 720XP
        id: 2
        mgmt_ip: 192.168.0.2
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet51]
        uplink_intreface_speed: 10000full
      jt-nm-mgt-3:
        platform: 7010T
        id: 3
        mgmt_ip: 192.168.0.3
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet52]
        uplink_intreface_speed: 10000full
      jt-nm-mgt-4:
        platform: 7010T
        id: 4
        mgmt_ip: 192.168.0.4
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet53]
        uplink_intreface_speed: 10000full
        